# Scikit-Learn

### Classification

Identifiying which category an object belongs to 
Application: Spam detection


### Regression

Predicting an attribute associated with an object 
Application : Stock prices prediction


### Clustering

Automatic grouping of smilar objects into sets
Application: Customer segmentation


### Model Selection

Comparing, Validating and choosing parameters and Model
Application: Parameter Tuning


### Dimensionality Reduction

Reducing the number of random variables to consider
Application : To Increase model efficiency


### Pre-Processing

Application: Transforming input data such as text for use with machine learning algorithms

In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
%matplotlib

Using matplotlib backend: MacOSX

In [7]:
wine = pd.read_csv('winequality-red.csv', sep=';')

In [9]:
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [10]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
fixed acidity           1599 non-null float64
volatile acidity        1599 non-null float64
citric acid             1599 non-null float64
residual sugar          1599 non-null float64
chlorides               1599 non-null float64
free sulfur dioxide     1599 non-null float64
total sulfur dioxide    1599 non-null float64
density                 1599 non-null float64
pH                      1599 non-null float64
sulphates               1599 non-null float64
alcohol                 1599 non-null float64
quality                 1599 non-null int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [12]:
wine.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [13]:
#preprocessing
bins = (2, 6.5, 8)
group_names = ['bad', 'good']
wine['quality'] = pd.cut(wine['quality'], bins= bins, labels = group_names)

In [15]:
wine['quality'].unique()

[bad, good]
Categories (2, object): [bad < good]

In [16]:
label_quality = LabelEncoder()

In [17]:
wine['quality'] = label_quality.fit_transform(wine['quality'])

In [19]:
wine.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,0
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,0
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,1
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,1
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,0

In [20]:
wine['quality'].value_counts()

0    1382
1     217
Name: quality, dtype: int64

In [28]:
sns.countplot(wine['quality'])

In [29]:
#seperate the dataset as response variable and feature variables
X = wine.drop('quality', axis=1)
y = wine['quality']

In [30]:
#Train and Test Splitting of data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
#Applying Standard scaling to get optimized result
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
X_train[:10]

array([[ 0.21833164,  0.88971201,  0.19209222,  0.30972563, -0.04964208,
         0.69100692,  1.04293362,  1.84669643,  1.09349989,  0.45822284,
         1.12317723],
       [-1.29016623, -1.78878251,  0.65275338, -0.80507963, -0.45521361,
         2.38847304,  3.59387025, -3.00449133, -0.40043872, -0.40119696,
         1.40827174],
       [ 1.49475291, -0.78434707,  1.01104539, -0.52637831,  0.59927236,
        -0.95796016, -0.99174203,  0.76865471, -0.07566946,  0.51551749,
        -0.58738978],
       [ 0.27635078,  0.86181102, -0.06383064, -0.66572897, -0.00908493,
         0.01202048, -0.71842739,  0.08948842,  0.05423824, -1.08873281,
        -0.96751578],
       [ 0.04427419,  2.81487994, -0.62686095,  2.39998549, -0.31326357,
        -0.47296984,  0.2229897 ,  1.1998714 ,  0.37900751, -0.9741435 ,
        -0.49235828],
       [-0.07176411, -0.78434707,  1.11341454, -0.17800167,  0.21397941,
         3.01896045,  2.62208486,  0.60694845,  0.44396136,  1.89058918,
        -0.58738978],
       [-1.17412793,  0.10848444, -0.62686095, -0.52637831, -0.23214927,
         0.98200112, -0.35400787, -1.95879086,  0.05423824,  0.91658007,
         1.12317723],
       [-0.1878024 , -0.17052541,  0.60156881,  0.03102432, -0.13075639,
        -0.37597178, -0.01995665,  0.93036097,  0.76873063, -0.229313  ,
         0.26789373],
       [-0.07176411,  0.61070216, -0.01264607, -0.38702766,  0.13286511,
        -1.05495822,  0.92146044,  0.37516948, -1.17988496, -0.229313  ,
        -1.25261029],
       [ 1.8428678 , -1.95618842,  1.21578369,  1.00647892,  0.31537229,
        -1.15195628, -0.71842739,  1.52328391, -0.20557717,  1.77599987,
        -0.30229528]])

## Random Forest Classifier

In [33]:
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [35]:
pred_rfc = rfc.predict(X_test)
pred_rfc[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [36]:
X_test[:20]

array([[-3.61859850e-01,  1.64286407e-01, -9.85152962e-01,
        -3.86510130e-02,  5.18158057e-01, -1.81975648e-01,
        -1.99566462e-02,  1.75731759e-01, -4.65392578e-01,
        -1.34389336e-04, -7.77452782e-01],
       [-3.03840702e-01, -1.70525408e-01, -5.24491803e-01,
        -6.65728970e-01, -1.30756387e-01,  4.97010797e-01,
         1.68066777e+00, -4.17191190e-01,  5.08915214e-01,
        -1.03143815e+00, -8.72484283e-01],
       [ 1.37871461e+00,  7.78108067e-01, -2.68568937e-01,
         1.00699644e-01,  3.76208022e-01,  1.09018543e-01,
        -3.84376165e-01,  1.95450060e+00, -2.05577167e-01,
         1.83329452e+00, -4.92358280e-01],
       [ 1.02293339e-01, -3.93733284e-01,  1.92092221e-01,
        -2.12839335e-01, -2.11870693e-01,  1.56398950e+00,
         3.44462872e-01,  6.60850535e-01,  1.19192097e-01,
        -6.87670232e-01, -5.87389780e-01],
       [-9.42051337e-01, -3.93733284e-01, -1.66199791e-01,
        -5.96053642e-01, -2.32149269e-01,  2.06016607e-01,
        -3.84376165e-01, -1.06401623e+00,  5.08915214e-01,
        -3.43902311e-01,  1.72862226e-01],
       [-6.51955593e-01, -6.72743130e-01,  1.40907648e-01,
        -3.17352327e-01, -1.10477811e-01,  1.85498369e+00,
         7.69618977e-01,  1.21829672e-01,  8.33684478e-01,
        -8.02259539e-01, -9.67515783e-01],
       [-3.61859850e-01,  5.26824689e-02, -6.38306444e-02,
        -4.56702985e-01,  1.11936473e-02,  6.91006925e-01,
         3.04724097e+00, -2.23143680e-01, -3.35484872e-01,
        -4.01196964e-01, -6.82421281e-01],
       [-7.67993891e-01,  1.39192973e+00, -9.85152962e-01,
        -3.87027656e-01,  9.23079528e-02, -5.69967902e-01,
        -8.39900563e-01, -6.32799535e-01,  5.73869067e-01,
        -1.08873281e+00, -3.97326779e-01],
       [-7.17641072e-02, -7.84347068e-01,  5.50384234e-01,
        -7.35404299e-01, -6.17442220e-01, -5.69967902e-01,
        -5.36217631e-01, -3.09387018e-01, -3.35484872e-01,
         4.58222839e-01, -5.87389780e-01],
       [-1.46422367e+00,  4.43296253e-01, -8.31599242e-01,
        -5.26378313e-01, -4.55213609e-01,  2.06016607e-01,
        -5.66585924e-01, -1.04784560e+00,  1.54817686e+00,
        -1.34389336e-04,  4.57956728e-01],
       [ 1.26267631e+00, -1.14723438e-01,  1.88118314e+00,
        -1.08326342e-01,  3.76208022e-01, -9.57960157e-01,
        -9.61373736e-01,  2.83535931e-01, -1.43970037e+00,
        -1.34389336e-04,  1.31324023e+00],
       [-9.42051337e-01,  1.28032579e+00, -1.29226040e+00,
        -5.26378313e-01, -2.11870693e-01, -9.57960157e-01,
        -1.05247862e+00, -4.17191190e-01,  1.54817686e+00,
        -1.72018350e-01, -4.44842529e-01],
       [-9.42051337e-01, -2.82129346e-01, -9.85152962e-01,
        -3.17352327e-01, -4.95770762e-01,  2.06016607e-01,
        -3.84376165e-01, -6.75921204e-01,  1.19192097e-01,
        -1.14723696e-01, -6.82421281e-01],
       [-7.67993891e-01,  1.64286407e-01, -7.29230096e-01,
        -6.65728970e-01, -2.32149269e-01,  8.85003052e-01,
        -1.41429819e-01, -2.60875140e-01,  1.84145950e-01,
        -4.01196964e-01, -1.15757878e+00],
       [-3.03840702e-01, -1.06335691e+00,  4.99199661e-01,
        -3.87027656e-01, -1.30756387e-01,  7.88004988e-01,
         3.44462872e-01, -2.01582845e-01,  1.84145950e-01,
        -4.01196964e-01, -9.67515783e-01],
       [ 3.34369933e-01, -1.39816873e+00,  9.08676246e-01,
        -5.96053642e-01, -4.34935033e-01, -8.60962093e-01,
        -1.05247862e+00, -1.74318251e+00, -4.00438725e-01,
        -6.30375579e-01,  1.78839774e+00],
       [-9.42051337e-01,  8.06009052e-01, -1.03633753e+00,
        -1.08326342e-01,  1.11936473e-02,  1.09018543e-01,
         1.07330191e+00, -5.24995363e-01,  2.49099803e-01,
        -6.87670232e-01, -3.02295278e-01],
       [ 1.03059972e+00, -5.61139191e-01,  6.52753380e-01,
         3.10243156e-02,  7.20293764e-02, -2.78973711e-01,
         1.62253113e-01,  8.44117628e-01, -5.95300283e-01,
        -1.14723696e-01, -3.97326779e-01],
       [ 6.24465676e-01, -1.28656479e+00,  1.47170655e+00,
         1.70374973e-01, -1.71313540e-01, -9.57960157e-01,
        -9.00637149e-01, -2.01582845e-01, -1.04997725e+00,
         1.48952660e+00,  1.21820873e+00],
       [ 4.42741900e-02,  1.19662284e+00, -8.31599242e-01,
        -4.56702985e-01,  3.14722237e-02,  1.20204793e-02,
         4.96304338e-01, -1.47680759e-01, -7.90161842e-01,
         9.16580068e-01, -7.77452782e-01]])

In [37]:
# Let's see how our model performed
print(classification_report(y_test,pred_rfc))
print(confusion_matrix(y_test,pred_rfc))

precision    recall  f1-score   support

           0       0.92      0.97      0.94       273
           1       0.74      0.49      0.59        47

    accuracy                           0.90       320
   macro avg       0.83      0.73      0.77       320
weighted avg       0.89      0.90      0.89       320

[[265   8]
 [ 24  23]]

## SVM Clssificier

In [39]:
clf = svm.SVC()
clf.fit(X_train, y_train)
pred_clf = clf.predict(X_test)

In [40]:
print(classification_report(y_test, pred_clf))
print(confusion_matrix(y_test,pred_clf))

precision    recall  f1-score   support

           0       0.88      0.98      0.93       273
           1       0.71      0.26      0.37        47

    accuracy                           0.88       320
   macro avg       0.80      0.62      0.65       320
weighted avg       0.86      0.88      0.85       320

[[268   5]
 [ 35  12]]

## Neural Network

In [41]:
mlpc = MLPClassifier(hidden_layer_sizes=(11, 11, 11), max_iter=500)
mlpc.fit(X_train, y_train)
pred_mlpc = mlpc.predict(X_test)

In [42]:
print(classification_report(y_test, pred_mlpc))
print(confusion_matrix(y_test,pred_mlpc))

precision    recall  f1-score   support

           0       0.93      0.93      0.93       273
           1       0.59      0.57      0.58        47

    accuracy                           0.88       320
   macro avg       0.76      0.75      0.75       320
weighted avg       0.88      0.88      0.88       320

[[254  19]
 [ 20  27]]

In [43]:
from sklearn.metrics import accuracy_score
cm = accuracy_score(y_test, pred_rfc)
cm

0.9

In [44]:
wine.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,0
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,0
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,1
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,1
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,0

In [46]:
Xnew = [[7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0]]
Xnew = sc.transform(Xnew)
ynew = rfc.predict(Xnew)	
ynew

array([1])

# Summary

```
- pd.read_csv()
- df.info()
- df.isnull().sum()
- pd.cut()
- LabelEncoder()
- LabelEncoder.fit_transform()
- df.value_counts()
- X = wine.drop('quality', axis=1) 
- y = wine['quality']
- X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
- sc = StandardScaler()
- X_train = sc.fit_transform(X_train)
- X_test = sc.transform(X_test)
```

#### RandomForest

- rfc = RandomForestClassifier(n_estimators=200)
- rfc.fit(X_train, y_train)
- pred_rfc = rfc.predict(X_test)
- print(classification_report(y_test, pred_clf))
- print(confusion_matrix(y_test,pred_clf))


#### SVM Clssificier
- clf = svm.SVC()
- clf.fit(X_train, y_train)
- pred_clf = clf.predict(X_test)
- print(classification_report(y_test, pred_clf))
- print(confusion_matrix(y_test,pred_clf))


#### Neural Network
- mlpc = MLPClassifier(hidden_layer_sizes=(11, 11, 11), max_iter=500)
- mlpc.fit(X_train, y_train)
- pred_mlpc = mlpc.predict(X_test)
- print(classification_report(y_test, pred_mlpc))
- print(confusion_matrix(y_test,pred_mlpc))